#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# ///
# Bake the badge's UI icons out of art.py into the cloud server as ONE
# TypeScript module of SVG geometry — server/src/lib/icon-art.ts.
#
# The public one-pager labels its cards with the same pictures the badge draws:
# a spoor on the jager card, two noses on snuffelen, a hand plucking a berry on
# plukken. They were emoji, which read as decoration from somewhere else.
#
# SVG rather than PNG (the road bake_server_art.sh takes for companions)
# because an ICONS entry is not a file: it is a grid of palette characters, so
# there is no PNG to inline and the geometry IS the source. As rects it scales
# to any card size with square pixels and no image-rendering rules, and the
# whole set is under 4 KB of the worker bundle.
#
# Only the icons the site asks for are baked — see WANTED. Adding a card means
# adding its name here and re-running.
#
# Usage:
#   scripts/bake_server_icons.sh            # (re-)bake
#   scripts/bake_server_icons.sh --check    # report drift, change nothing
#                                           # (exit 1 if out of date — CI)
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "com.enigmeta.foxhunt" / "assets" / "art.py"
OUT = ROOT / "server" / "src" / "lib" / "icon-art.ts"

WANTED = ["spoor", "sig", "pluk", "bes", "dans", "snuf", "spark"]

HEADER = """\
// GENERATED by scripts/bake_server_icons.sh, do not edit.
//
// The badge's own UI icons (art.py ICONS) as SVG geometry: one entry per
// icon, its grid size plus horizontal runs of same-coloured pixels. <Icon>
// in components/Icon.tsx draws each run as a <rect>.

export interface IconArt {
  w: number;
  h: number;
  /** [x, y, width, colour] — one horizontal run of pixels, height 1. */
  runs: [number, number, number, string][];
}

export const ICON_ART: Record<string, IconArt> = {
"""


def read_icons():
    """art.py imports lvgl, so it cannot be imported here — parse it instead.

    ICONS is a dict literal followed by a few alias assignments
    (ICONS["bes"] = ICONS["food"]), which is the whole shape this handles.
    Anything else in there is skipped rather than guessed at."""
    tree = ast.parse(SRC.read_text())
    icons = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if isinstance(target, ast.Name) and target.id == "ICONS":
            icons = ast.literal_eval(node.value)
        # ICONS["bes"] = ICONS["food"] — the glossary aliases
        elif (
            isinstance(target, ast.Subscript)
            and isinstance(target.value, ast.Name)
            and target.value.id == "ICONS"
            and isinstance(node.value, ast.Subscript)
            and isinstance(node.value.value, ast.Name)
            and node.value.value.id == "ICONS"
        ):
            src = ast.literal_eval(node.value.slice)
            if src in icons:
                icons[ast.literal_eval(target.slice)] = icons[src]
    return icons


def runs_for(icon):
    """Merge each row into horizontal runs of one colour. An 8x8 icon is ~10
    runs instead of ~40 rects, and the seams between them are what
    shape-rendering: crispEdges has to hold together."""
    rows, pal = icon["rows"], icon["pal"]
    out = []
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            ch = row[x]
            run = 1
            while x + run < len(row) and row[x + run] == ch:
                run += 1
            if ch in pal:
                out.append((x, y, run, "#%06x" % pal[ch]))
            x += run
    return out


def bake():
    icons = read_icons()
    missing = [n for n in WANTED if n not in icons]
    if missing:
        sys.exit("art.py has no icon named: %s" % ", ".join(missing))

    body = []
    for name in WANTED:
        icon = icons[name]
        runs = ", ".join('[%d, %d, %d, "%s"]' % r for r in runs_for(icon))
        body.append(
            "  %s: { w: %d, h: %d, runs: [%s] },\n"
            % (name, len(icon["rows"][0]), len(icon["rows"]), runs)
        )
    return (HEADER + "".join(body) + "};\n").encode()


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        print("usage: %s [--check]" % sys.argv[0], file=sys.stderr)
        return 2

    want = bake()
    if OUT.exists() and OUT.read_bytes() == want:
        return 0
    if check:
        print("stale: %s" % OUT if OUT.exists() else "missing: %s" % OUT)
        print("server icons out of date — run scripts/bake_server_icons.sh", file=sys.stderr)
        return 1
    print("baking: %s" % OUT)
    OUT.write_bytes(want)
    return 0


if __name__ == "__main__":
    sys.exit(main())
