#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# ///
# Bake artwork/companions/*.png into the cloud server as ONE TypeScript module
# of data URIs — server/src/lib/companion-art.ts.
#
# Inlined rather than copied into server/static/ for two reasons:
#
#   1. Filenames leak. static/ is public, and the companion heads include
#      konijn.png and varken.png — two names that are also in the creature
#      roster. CLAUDE.md's rule ("the public site must not hold the roster",
#      "never copy artwork/animals/ into server/static/") is about art, but a
#      path in view-source spoils exactly as well. A data URI has no path.
#   2. One companion is a head plus up to ten accessories. As files that is up
#      to eleven requests per avatar, and /debug/players draws one per row.
#      All fifteen layers together are 2.7 KB of PNG — under 4 KB base64, so
#      the whole set ships once, inside the worker bundle, and costs nothing.
#
# Only the layers companion.py names are baked; the sprite atlas keeps the
# same PNGs for the badge (scripts/bake_sprites.sh). Both read artwork/.
#
# Usage:
#   scripts/bake_server_art.sh            # (re-)bake
#   scripts/bake_server_art.sh --check    # report drift, change nothing
#                                         # (exit 1 if out of date — CI)
import base64
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "artwork" / "companions"
OUT = ROOT / "server" / "src" / "lib" / "companion-art.ts"

HEADER = """\
// GENERATED by scripts/bake_server_art.sh, do not edit.
//
// Every companion layer from artwork/companions/, as a 16x16 PNG data URI
// keyed by its part id — the same id companion.ts and the badge's
// companion.py use. Inline, not files under static/: see the script.

export const COMPANION_ART: Record<string, string> = {
"""


def bake():
    lines = []
    for png in sorted(SRC.glob("*.png")):
        b64 = base64.b64encode(png.read_bytes()).decode()
        lines.append('  %s: "data:image/png;base64,%s",\n' % (png.stem, b64))
    return (HEADER + "".join(lines) + "};\n").encode()


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        print("usage: %s [--check]" % sys.argv[0], file=sys.stderr)
        return 2

    want = bake()
    if OUT.exists() and OUT.read_bytes() == want:
        return 0
    if check:
        print("stale: %s" % OUT if OUT.exists() else "missing: %s" % OUT)
        print("server art out of date — run scripts/bake_server_art.sh", file=sys.stderr)
        return 1
    print("baking: %s" % OUT)
    OUT.write_bytes(want)
    return 0


if __name__ == "__main__":
    sys.exit(main())
