#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow"]
# ///
# Bake the artwork into the files the app loads. A Python script behind a .sh
# name: the shebang hands it to `uv run --script`, which reads the inline
# metadata above — callers just run it, no wrapper needed. Two kinds of output:
#
#   16px-tall PNGs   -> ONE atlas: assets/sprites.bin + assets/atlas.py
#                       ...but only under SPRITE_DIRS; see there
#   everything else  -> mirrored PNG, same tree (title-screen)
#
# artwork/ is the source of truth (PNGs plus their .aseprite sources). The
# atlas exists because LittleFS bills a 4 KB block per file and a deploy pays
# ~0.28 s to hash each one — 40+ tiny sprites cost ~160 KB and ~12 s as files,
# ~64 KB and nothing as one blob.
#
# Atlas format: sprites.bin is bare 16x16 frames, 1024 bytes each (BGRA — the
# byte order LVGL's little-endian ARGB8888 wants), concatenated in atlas.py's
# order. A PNG wider than 16 is a sprite SHEET: width N*16 = N consecutive
# frames, left to right — that is how an animal gets animation frames. The
# key is the artwork-relative path ("animals/vos.png"), so the index reads
# like the file tree it replaced. art.py seeks frame*1024 and hands LVGL the
# raw bytes; no PNG decode, no per-sprite file.
#
# Usage:
#   scripts/bake_sprites.sh            # (re-)bake everything, prune orphans
#   scripts/bake_sprites.sh --check    # report drift, change nothing
#                                      # (exit 1 if out of date — CI)
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "artwork"
OUT = ROOT / "be.fri3d.foxhunt" / "assets"
BIN = OUT / "sprites.bin"
INDEX = OUT / "atlas.py"

FRAME = 16  # sprite grid; a sheet is N of these side by side
FRAME_BYTES = FRAME * FRAME * 4

# The only folders the app can address. art.py builds exactly two atlas keys —
# "animals/" + creature["img"] and "companions/" + part_id — so a sprite
# anywhere else has no code path that can ever draw it.
#
# This is an allowlist, not a glob, on purpose. artwork/ never ships (the
# deploy stages be.fri3d.foxhunt/ only), but the atlas launders whatever it
# holds onto the badge — and packing many files into one destroyed the audit
# surface that used to make that obvious. `ls assets/` once told you what
# shipped; now it says "sprites.bin". Guest art under artwork/fien and
# artwork/fran rode along unnoticed that way: 23 unreachable frames, 23 KB.
# Adding a folder here is a deliberate act; dropping a PNG in one is not.
SPRITE_DIRS = ("animals", "companions")

INDEX_HEADER = """\
# atlas.py — GENERATED by scripts/bake_sprites.sh, do not edit.
#
# key: artwork-relative path -> (first frame index, frame count) into
# sprites.bin; a frame is 1024 bytes of 16x16 BGRA at index*1024.

SPRITES = {
"""


def is_sprite(im):
    return im.height == FRAME and im.width % FRAME == 0


def frames(im):
    """Split a sheet into per-frame BGRA byte blocks, left to right."""
    rgba = im.convert("RGBA")
    return [
        rgba.crop((x, 0, x + FRAME, FRAME)).tobytes("raw", "BGRA")
        for x in range(0, im.width, FRAME)
    ]


def bake():
    """Compute every output in memory: ({relpath under assets: bytes},
    [sprites skipped as unaddressable])."""
    blob = bytearray()
    index_lines = []
    mirror = {}
    skipped = []
    for png in sorted(SRC.rglob("*.png")):
        rel = png.relative_to(SRC).as_posix()
        with Image.open(png) as im:
            if is_sprite(im):
                # Unaddressable folder: skip it entirely rather than fall
                # through to the mirror branch, which would ship it as a PNG
                # and cost a 4 KB block for art nothing can draw.
                if rel.split("/")[0] not in SPRITE_DIRS:
                    skipped.append(rel)
                    continue
                fr = frames(im)
                index_lines.append(
                    '    "%s": (%d, %d),\n' % (rel, len(blob) // FRAME_BYTES, len(fr))
                )
                for f in fr:
                    blob += f
            else:
                mirror[rel] = png.read_bytes()
    out = dict(mirror)
    out[BIN.name] = bytes(blob)
    out[INDEX.name] = (INDEX_HEADER + "".join(index_lines) + "}\n").encode()
    return out, skipped


def main():
    check = sys.argv[1:] == ["--check"]
    if sys.argv[1:] and not check:
        print("usage: %s [--check]" % sys.argv[0], file=sys.stderr)
        return 2

    want, skipped = bake()
    fail = 0

    # Say so out loud when art is left behind — the whole reason fien/ and
    # fran/ shipped for months is that nothing ever mentioned them. Only on a
    # real bake: this is configured behaviour, not drift, so --check stays
    # quiet for CI.
    if skipped and not check:
        print(
            "skipping %d sprite(s) outside %s (unreachable — no code path "
            "builds those keys):" % (len(skipped), "/".join(SPRITE_DIRS))
        )
        for rel in skipped:
            print("  - artwork/%s" % rel)

    for rel, data in sorted(want.items()):
        path = OUT / rel
        if path.exists() and path.read_bytes() == data:
            continue
        if check:
            print("stale: %s" % path if path.exists() else "missing: %s" % path)
            fail = 1
        else:
            print("baking: %s" % path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

    # A PNG under assets/ with no artwork behind it is unmaintainable — prune.
    # (Only PNGs: .py, fonts/*.bin and sprites.bin are not this script's to
    # delete, except the two files it generates, handled above.)
    for path in sorted(OUT.rglob("*.png")):
        rel = path.relative_to(OUT).as_posix()
        if rel in want:
            continue
        if check:
            print("orphan: %s (no artwork/%s)" % (path, rel))
            fail = 1
        else:
            print("pruning: %s" % path)
            path.unlink()
    if not check:
        for d in sorted((p for p in OUT.rglob("*") if p.is_dir()), reverse=True):
            if not any(d.iterdir()):
                d.rmdir()

    if check and fail:
        print("artwork out of date — run scripts/bake_sprites.sh", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
