#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

repo_root="$(cd .. && pwd)"
target="$repo_root/server/src/lib/discovery-art.ts"
temporary="$(mktemp "${TMPDIR:-/tmp}/foxhunt-discovery-art.XXXXXX")"

mode="write"
case "${1:-}" in
    "") mode="write" ;;
    --check) mode="check" ;;
    *) echo "usage: $0 [--check]" >&2; exit 2 ;;
esac

cleanup() {
    rm -f "$temporary"
}
trap cleanup EXIT

DISCOVERY_REPO_ROOT="$repo_root" \
    uv run --quiet --with pillow python - <<'PY' >"$temporary"
import base64
import io
import os
import runpy
from pathlib import Path

from PIL import Image

root = Path(os.environ["DISCOVERY_REPO_ROOT"])
roster = runpy.run_path(root / "com.enigmeta.foxhunt/assets/creatures.py")["CREATURES"]

print("// GENERATED by scripts/bake_discovery_art.sh, do not edit.")
print("//")
print("// Ordinary creatures keep their first artwork frame. Rare and legendary")
print("// creatures are flattened to an anonymous silhouette before being inlined;")
print("// the public server never receives their full-colour artwork or filenames.")
print()
print("export const DISCOVERY_ART: Record<number, string> = {")

for creature in roster:
    source = root / "artwork/animals" / creature["img"]
    with Image.open(source) as opened:
        frame = opened.convert("RGBA").crop((0, 0, 16, 16))

    if creature["rarity"] != "norm":
        frame.putdata(
            [
                (58, 74, 52, alpha) if alpha else (0, 0, 0, 0)
                for _red, _green, _blue, alpha in frame.get_flattened_data()
            ]
        )

    encoded = io.BytesIO()
    frame.save(encoded, "PNG", optimize=True)
    data = base64.b64encode(encoded.getvalue()).decode("ascii")
    print(f'  {creature["id"]}: "data:image/png;base64,{data}",')

print("};")
PY

if [[ "$mode" == "check" ]]; then
    if [[ ! -f "$target" ]] || ! cmp -s "$temporary" "$target"; then
        echo "stale: $target" >&2
        echo "discovery art is out of date — run scripts/bake_discovery_art.sh" >&2
        exit 1
    fi
else
    mv "$temporary" "$target"
    trap - EXIT
    echo "baked: $target"
fi
