# creatures.py — the beast roster. Pure data, no LVGL, runs anywhere.
#
# rarity  : "norm" | "rare" | "leg"
# code    : 4-digit code on the physical fox (checked offline for now)
# beacon  : LoRa beacon id the real radio backend will key on
# soort   : dossier "species" blurb
# biotoop : dossier habitat
# favoriet: favourite food ("bes" | "noot" | "eikel") — feeding it grants +band
# weetje  : a fun fact shown on the dossier
# img     : the creature's art — filename under artwork/animals/ (art.py owns
#           the folder). The 1_/2_/3_ prefix mirrors the tier: base/rare/leg.
# anim    : True when img is a sprite SHEET (width N*16 = N frames) that
#           should play — on the win/celebrate payoff and the beast page.
#           The frame count lives in the baked atlas, not here.
#
# List order is book order (base, rare, legendary); ids are the wire identity
# and do not follow it.

CREATURES = [
    # ── base ────────────────────────────────────────────────────────────
    {
        "id": 0,
        "naam": "Vos",
        "rarity": "norm",
        "code": "1234",
        "beacon": 0,
        "img": "1_vos.png",
        "soort": "Sluiper",
        "biotoop": "Beukenbos",
        "favoriet": "bes",
        "weetje": "De Vos jaagt het liefst in de schemering.",
    },
    {
        "id": 1,
        "naam": "Egel",
        "rarity": "norm",
        "code": "2345",
        "beacon": 1,
        "img": "1_egel.png",
        "soort": "Snuffelaar",
        "biotoop": "Heggen",
        "favoriet": "eikel",
        "weetje": "De Egel rolt zich op als hij schrikt.",
    },
    {
        "id": 2,
        "naam": "Kat",
        "rarity": "norm",
        "code": "0123",
        "beacon": 2,
        "img": "1_kat.png",
        "soort": "Sluiper",
        "biotoop": "Schuur",
        "favoriet": "bes",
        "weetje": "De Kat slaapt het liefst in de zon.",
    },
    {
        "id": 3,
        "naam": "Axolotl",
        "rarity": "norm",
        "code": "4812",
        "beacon": 3,
        "img": "1_axolotl.png",
        "soort": "Grijnzer",
        "biotoop": "Stille poel",
        "favoriet": "bes",
        "weetje": "De Axolotl lacht altijd, zelfs onder water.",
    },
    {
        "id": 4,
        "naam": "Capybara",
        "rarity": "norm",
        "code": "9273",
        "beacon": 4,
        "img": "1_capybara.png",
        "soort": "Chiller",
        "biotoop": "Rivieroever",
        "favoriet": "noot",
        "weetje": "De Capybara blijft rustig, wat er ook gebeurt.",
    },
    {
        "id": 5,
        "naam": "Koe",
        "rarity": "norm",
        "code": "3581",
        "beacon": 5,
        "img": "1_cow.png",
        "soort": "Grazer",
        "biotoop": "Weide",
        "favoriet": "eikel",
        "weetje": "De Koe herkauwt elke hap wel vier keer.",
    },
    {
        "id": 6,
        "naam": "Hond",
        "rarity": "norm",
        "code": "6147",
        "beacon": 6,
        "img": "1_dog.png",
        "soort": "Kwispelaar",
        "biotoop": "Boerenerf",
        "favoriet": "noot",
        "weetje": "De Hond ruikt je al van drie velden ver.",
    },
    {
        "id": 7,
        "naam": "Eend",
        "rarity": "norm",
        "code": "8365",
        "beacon": 7,
        "img": "1_duck.png",
        "soort": "Snateraar",
        "biotoop": "Vijver",
        "favoriet": "bes",
        "weetje": "De Eend slaapt met een oog open.",
    },
    {
        "id": 8,
        "naam": "Kip",
        "rarity": "norm",
        "code": "2906",
        "beacon": 8,
        "img": "1_kip.png",
        "soort": "Scharrelaar",
        "biotoop": "Kippenren",
        "favoriet": "noot",
        "weetje": "De Kip vertelt het hele erf wanneer ze een ei legt.",
    },
    {
        "id": 9,
        "naam": "Koala",
        "rarity": "norm",
        "code": "7429",
        "beacon": 9,
        "img": "1_koala.png",
        "soort": "Slaper",
        "biotoop": "Boomtop",
        "favoriet": "eikel",
        "weetje": "De Koala slaapt wel twintig uur per dag.",
    },
    {
        "id": 10,
        "naam": "Konijn",
        "rarity": "norm",
        "code": "5063",
        "beacon": 10,
        "img": "1_konijn.png",
        "soort": "Huppelaar",
        "biotoop": "Duinen",
        "favoriet": "bes",
        "weetje": "Het Konijn hoort je aankomen met z'n lange oren.",
    },
    {
        "id": 11,
        "naam": "Varken",
        "rarity": "norm",
        "code": "1738",
        "beacon": 11,
        "img": "1_pig.png",
        "soort": "Wroeter",
        "biotoop": "Modderpoel",
        "favoriet": "eikel",
        "weetje": "Het Varken vindt eikels diep onder de grond.",
    },
    # ── new base ───────────────────────────────────────────────────────
    {
        "id": 22,
        "naam": "Aap",
        "rarity": "norm",
        "code": "8642",
        "beacon": 22,
        "img": "1_aap.png",
        "soort": "Klimmer",
        "biotoop": "Boomkruin",
        "favoriet": "noot",
        "weetje": "De Aap gebruikt zijn staart als extra hand.",
    },
    {
        "id": 23,
        "naam": "Giraf",
        "rarity": "norm",
        "code": "3159",
        "beacon": 23,
        "img": "1_giraf.png",
        "soort": "Bladeraar",
        "biotoop": "Savanne",
        "favoriet": "bes",
        "weetje": "De Giraf ziet over elke struik en boom heen.",
    },
    {
        "id": 24,
        "naam": "Papegaai",
        "rarity": "norm",
        "code": "7042",
        "beacon": 24,
        "img": "1_papegaai.png",
        "soort": "Naprater",
        "biotoop": "Regenwoud",
        "favoriet": "noot",
        "weetje": "De Papegaai onthoudt elk geluid dat hij hoort.",
    },
    # ── rare ────────────────────────────────────────────────────────────
    {
        "id": 16,
        "naam": "Everzwaan",
        "rarity": "rare",
        "code": "7391",
        "beacon": 16,
        "img": "2_everzwaan.png",
        "soort": "Plonzer",
        "biotoop": "Moeras",
        "favoriet": "bes",
        "weetje": "De Everzwaan poetst z'n veren met modder.",
    },
    {
        "id": 17,
        "naam": "Kameleeuw",
        "rarity": "rare",
        "code": "4567",
        "beacon": 17,
        "img": "2_kameleeuw.png",
        "soort": "Kleurling",
        "biotoop": "Varens",
        "favoriet": "bes",
        "weetje": "De Kameleeuw verkleurt als hij blij is.",
    },
    {
        "id": 18,
        "naam": "Koekoekoek",
        "rarity": "rare",
        "code": "8250",
        "beacon": 18,
        "img": "2_koekoekoek.png",
        "soort": "Roeper",
        "biotoop": "Boomgaard",
        "favoriet": "noot",
        "weetje": "De Koekoekoek kraait elk uur, maar nooit op tijd.",
    },
    {
        "id": 19,
        "naam": "Konijlpaard",
        "rarity": "rare",
        "code": "6789",
        "beacon": 19,
        "img": "2_konijlpaard.png",
        "soort": "Springer",
        "biotoop": "Weide",
        "favoriet": "noot",
        "weetje": "Het Konijlpaard springt over hoge struiken.",
    },
    {
        "id": 20,
        "naam": "Slakamander",
        "rarity": "rare",
        "code": "3914",
        "beacon": 20,
        "img": "2_slakamander.png",
        "soort": "Kruiper",
        "biotoop": "Nat mos",
        "favoriet": "bes",
        "weetje": "De Slakamander draagt z'n huisje overal mee naartoe.",
    },
    {
        "id": 21,
        "naam": "Tijghert",
        "rarity": "rare",
        "code": "5678",
        "beacon": 21,
        "img": "2_tijghert.png",
        "soort": "Renner",
        "biotoop": "Open plek",
        "favoriet": "eikel",
        "weetje": "Het Tijghert rent sneller dan de wind.",
    },
    # ── legendary ───────────────────────────────────────────────────────
    {
        "id": 12,
        "naam": "Knoricorn",
        "rarity": "leg",
        "code": "0007",
        "beacon": 12,
        "img": "3_knoricorn.png",
        "anim": True,
        "soort": "Eenhoorn",
        "biotoop": "Regenboogwei",
        "favoriet": "bes",
        "weetje": "De Knoricorn verschijnt enkel voor wie nooit opgeeft.",
    },
    {
        "id": 13,
        "naam": "Glitch Vos",
        "rarity": "leg",
        "code": "1337",
        "beacon": 13,
        "img": "3_glitch_vos.png",
        "anim": True,
        "soort": "Storing",
        "biotoop": "Tussen de pixels",
        "favoriet": "noot",
        "weetje": "De Glitch Vos flikkert tussen twee werelden.",
    },
    {
        "id": 14,
        "naam": "Party Vos",
        "rarity": "leg",
        "code": "9876",
        "beacon": 14,
        "img": "3_party_vos.png",
        "anim": True,
        "soort": "Feestbeest",
        "biotoop": "Dansvloer",
        "favoriet": "bes",
        "weetje": "De Party Vos danst tot de zon weer opkomt.",
    },
    {
        "id": 15,
        "naam": "Zwarte Vos",
        "rarity": "leg",
        "code": "0413",
        "beacon": 15,
        "img": "3_zwarte_vos.png",
        "anim": True,
        "soort": "Schaduw",
        "biotoop": "Donker bos",
        "favoriet": "noot",
        "weetje": "De Zwarte Vos zie je pas als hij dat wil.",
    },
    {
        "id": 25,
        "naam": "Dolfenix",
        "rarity": "leg",
        "code": "2608",
        "beacon": 25,
        "img": "3_dolfenix.png",
        "anim": True,
        "soort": "Vuurvin",
        "biotoop": "Vulkanische zee",
        "favoriet": "bes",
        "weetje": "De Dolfenix duikt door golven en herrijst uit het schuim.",
    },
    {
        "id": 26,
        "naam": "Kraaiken",
        "rarity": "leg",
        "code": "0808",
        "beacon": 26,
        "img": "3_kraaiken.png",
        "anim": True,
        "soort": "Inktkraai",
        "biotoop": "Mistige haven",
        "favoriet": "noot",
        "weetje": "Het Kraaiken kraakt een noot met acht armen tegelijk.",
    },
]


def by_id(cid):
    for c in CREATURES:
        if c["id"] == cid:
            return c
    return None


def starter_for(badge_id):
    """The startbeest this badge is destined for: a base-tier creature picked
    by FNV-1a over the canonical badge id, so a re-registration can never
    reroll it. MUST stay in step with the server's copy (server/src/lib/
    starter.ts) — the server runs the same hash over the same lowercased id,
    and both sides landing on the same creature is what lets an offline
    registration converge on sync."""
    h = 0x811C9DC5
    for b in badge_id.strip().lower().encode():
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    base = sorted(c["id"] for c in CREATURES if c["rarity"] == "norm")
    return base[h % len(base)]
